apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeverse-deployment
  labels:
    app: homeverse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homeverse
  template:
    metadata:
      labels:
        app: homeverse
    spec:
      containers:
      - name: homeverse
        image: AbhishekA2077/homeverse:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: homeverse-service
spec:
  selector:
    app: homeverse
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort
